### ISSUE TITLE
[Errno 2] No such file or directory: 'chnroute.txt'

### ISSUE THREAD

**Issue by BirkhoffLee** [Siujoeng-Lau/Encrypted-DNS#3]
**Describe the bug**
`chnroute.txt` not found after startup.

```
$ sudo encrypted-dns
Starting Encrypted-DNS Resolver
Traceback (most recent call last):
  File "/usr/local/bin/encrypted-dns", line 8, in <module>
    sys.exit(start())
  File "/usr/local/lib/python3.7/site-packages/encrypted_dns/main.py", line 9, in start
    dns_controller = encrypted_dns.server.Controller(dns_config_object)
  File "/usr/local/lib/python3.7/site-packages/encrypted_dns/server/controller.py", line 25, in __init__
    self.net_list = [line.rstrip('\n') for line in open('chnroute.txt')]
FileNotFoundError: [Errno 2] No such file or directory: 'chnroute.txt'
```

**To Reproduce**
Follow the README installation guide, edit the configurations and start again.

**Expected behavior**
It should launch successfully.

**Desktop (please complete the following information):**
 - Python Version 3.7.5
 - Encrypted-DNS Version 1.0.0

**Comment by Siujoeng-Lau** [comment]
I forgot to include this file into the Python package...
By the way, if you are living outside mainland China, you could set 'dns_bypass_china' to False, since this feature is only used to prevent DNS poisoning in China.

**Comment by BirkhoffLee** [comment]
Makes sense. Are you planning to add back the missing file soon?

**Comment by Siujoeng-Lau** [comment]
> Makes sense. Are you planning to add back the missing file soon?
> […](#)
> On Dec 8, 2019, 5:05 PM +0800, Xiaoyang Liu ***@***.***>, wrote: I forgot to include this file into the Python package... By the way, if you are living outside mainland China, you could set 'dns_bypass_china' to False, since this feature is only used to prevent DNS poisoning in China. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes, I will add the file back as soon as possible.

**Comment by Siujoeng-Lau** [comment]
Already released new version.

**Comment by BirkhoffLee** [comment]
```                                                                                                                                                                                            $ python3 -m pip install --upgrade encrypted-dns
Requirement already up-to-date: encrypted-dns in /usr/local/lib/python3.7/site-packages (1.1.0)
$ sudo encrypted-dns
Starting Encrypted-DNS 1.1.0
Load config file: /Users/birkhoff/.config/encrypted_dns/config.json
Traceback (most recent call last):
  File "/usr/local/bin/encrypted-dns", line 8, in <module>
    sys.exit(start())
  File "/usr/local/lib/python3.7/site-packages/encrypted_dns/main.py", line 9, in start
    dns_controller = encrypted_dns.server.Controller(dns_config_object)
  File "/usr/local/lib/python3.7/site-packages/encrypted_dns/server/controller.py", line 25, in __init__
    self.net_list = [line.rstrip('\n') for line in open('chnroute.txt')]
FileNotFoundError: [Errno 2] No such file or directory: 'chnroute.txt'
```

Hmmm...

**Comment by Siujoeng-Lau** [comment]
> ```
> $ python3 -m pip install --upgrade encrypted-dns
> Requirement already up-to-date: encrypted-dns in /usr/local/lib/python3.7/site-packages (1.1.0)
> $ sudo encrypted-dns
> Starting Encrypted-DNS 1.1.0
> Load config file: /Users/birkhoff/.config/encrypted_dns/config.json
> Traceback (most recent call last):
>   File "/usr/local/bin/encrypted-dns", line 8, in <module>
>     sys.exit(start())
>   File "/usr/local/lib/python3.7/site-packages/encrypted_dns/main.py", line 9, in start
>     dns_controller = encrypted_dns.server.Controller(dns_config_object)
>   File "/usr/local/lib/python3.7/site-packages/encrypted_dns/server/controller.py", line 25, in __init__
>     self.net_list = [line.rstrip('\n') for line in open('chnroute.txt')]
> FileNotFoundError: [Errno 2] No such file or directory: 'chnroute.txt'
> ```
> 
> Hmmm...

Reinstall the package and try again...

**Comment by BirkhoffLee** [comment]
@Siujoeng-Lau I uninstalled and installed the package, removed the old config file but still getting this:

```
$ sudo encrypted-dns
Starting Encrypted-DNS 1.1.3
Load config file: /Users/birkhoff/.config/encrypted_dns/config.json
Plain DNS Server listening on: 127.0.0.1:5300
[Error] [Errno 2] No such file or directory: 'filter_lists/chnroute.txt'
```

Where exactly should I put that file?

**Comment by Siujoeng-Lau** [comment]
> @Siujoeng-Lau I uninstalled and installed the package, removed the old config file but still getting this:
> 
> ```
> $ sudo encrypted-dns
> Starting Encrypted-DNS 1.1.3
> Load config file: /Users/birkhoff/.config/encrypted_dns/config.json
> Plain DNS Server listening on: 127.0.0.1:5300
> [Error] [Errno 2] No such file or directory: 'filter_lists/chnroute.txt'
> ```
> 
> Where exactly should I put that file?

Just ignore that error message. I think the program works well now..
